export const footerData = [
  {
    title: 'Now showing',
    links: [
      'The Fantastic Four: First Steps',
      'The Naked Gun',
      'Jurassic World: Rebirth',
      'Superman',
      'Alle films',
    ],
  },
  {
    title: 'Cinema in your cities',
    links: [
      'Filmpalast in Berlin',
      'Arthaus Kino in Hamburgo',
      'CineStar in Munish',
      'Luxor in Koln',
      'CinemaxX in Frankfurt',
      'All cinemas',
    ],
  },
  {
    title: 'ABOUT',
    links: [
      'Club Oz',
      'Subscriptions',
      'More from Oz',
      'Specials & Events',
      'IMAX',
      '4DX',
      'Dolby Cinema',
      'Dolby Atmos',
      'ScreenX',
      'Oz Filmfeestje',
      'News',
    ],
  },
  {
    title: 'USEFUL LINKS',
    links: [
      'Klantenservice',
      'OzGiftcard',
      'Oz Voucherchecker',
      'Mijn Club Oz account',
      'Werken bij Oz',
      'Oz Thuis',
      'Oz Business',
      'Go!Gaming',
      'X-CUBE',
      'Pers',
      'Adverteren',
      'MVO',
    ],
  },
  {
    title: 'TERMS & CONDITIONS',
    links: [
      'All terms & conditions',
      'Privacy statement',
      'Cookies',
      'Cookie Statement',
      'CVD',
      'Accesibility',
    ],
  },
];
