const month = new Date().toLocaleDateString('en-EN', { month: 'short' });
export const days = [
  `FRI 01 ${month.toUpperCase()}`,
  `SAT 02 ${month.toUpperCase()}`,
  `SON 03 ${month.toUpperCase()}`,
  `MON 04 ${month.toUpperCase()}`,
  `TUE 05 ${month.toUpperCase()}`,
  `WED 06 ${month.toUpperCase()}`,
  `THU 07 ${month.toUpperCase()}`,
  `FRI 08 ${month.toUpperCase()}`,
  `SAT 09 ${month.toUpperCase()}`,
  `SON 10 ${month.toUpperCase()}`,
  `MON 11 ${month.toUpperCase()}`,
  `TUE 12 ${month.toUpperCase()}`,
  `WED 13 ${month.toUpperCase()}`,
  `THU 14 ${month.toUpperCase()}`,
  `FRI 15 ${month.toUpperCase()}`,
  `SAT 16 ${month.toUpperCase()}`,
  `SON 17 ${month.toUpperCase()}`,
  `MON 18 ${month.toUpperCase()}`,
  `TUE 19 ${month.toUpperCase()}`,
  `WED 20 ${month.toUpperCase()}`,
  `THU 21 ${month.toUpperCase()}`,
  `FRI 22 ${month.toUpperCase()}`,
  `SAT 23 ${month.toUpperCase()}`,
  `SON 24 ${month.toUpperCase()}`,
  `MON 25 ${month.toUpperCase()}`,
  `TUE 26 ${month.toUpperCase()}`,
  `WED 27 ${month.toUpperCase()}`,
  `THU 28 ${month.toUpperCase()}`,
  `FRI 29 ${month.toUpperCase()}`,
  `SAT 30 ${month.toUpperCase()}`,
  `SON 31 ${month.toUpperCase()}`,
];
